@ToDoItems_HostAddress = https://localhost:7279

GET {{ToDoItems_HostAddress}}/api/todo-items

###

POST {{ToDoItems_HostAddress}}/api/todo-items
Content-Type: application/json
{
    "description": "Wash your hands",
    "assignedTo": "Ben Mitelman"
}

###

@index=0
PUT {{ToDoItems_HostAddress}}/api/todo-items/{{index}}
Content-Type: application/json

{
    "description": "Wash your hands",
    "assignedTo": "Ben Mitelman"
}

###

GET {{ToDoItems_HostAddress}}/api/todo-items/{{index}}

###

DELETE {{ToDoItems_HostAddress}}/api/todo-items/{{index}}

###

@sortOrder=asc
GET {{ToDoItems_HostAddress}}/api/todo-items/sorted?sortOrder={{sortOrder}}

###

GET {{ToDoItems_HostAddress}}/api/todo-items/sorted?sortOrder=desc

###
