@HostAddress = https://localhost:7279

GET {{HostAddress}}/todoitems

###

POST {{HostAddress}}/todoitems
Content-Type: application/json

"Go to eat"

###

PUT {{HostAddress}}/todoitems/2
Content-Type: application/json

"brush my hands"

###

DELETE {{HostAddress}}/todoitems/0

###

GET {{HostAddress}}/todoitems/sorted?sortOrder=asc

###

GET {{HostAddress}}/todoitems/sorted?sortOrder=desc