@ToDoItems_HostAddress = https://localhost:7279

GET {{ToDoItems_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ToDoItems_HostAddress}}/todoitems

###

POST {{ToDoItems_HostAddress}}/todoitems
Content-Type: application/json

"brush my teeth"

###

PUT {{ToDoItems_HostAddress}}/todoitems/0
Content-Type: application/json

"brush my teeth"

###

DELETE {{ToDoItems_HostAddress}}/todoitems/0

###

GET {{ToDoItems_HostAddress}}/todoitems/sorted?sortOrder=asc

###

GET {{ToDoItems_HostAddress}}/todoitems/sorted?sortOrder=desc