import {themes as prismThemes} from 'prism-react-renderer';
import type {Config} from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/** Doc IDs to omit from autogenerated sidebars (pages are still built and linkable). */
const DOC_IDS_EXCLUDED_FROM_SIDEBAR = new Set<string>([
  'Web API/01_01_AttributesVSFilters',
  'Web API/01_02_routing',
]);

const config: Config = {
  title: 'ASP.NET Core And More',
  tagline: 'Main concepts in ASP.NET Core and more',
  favicon: 'img/favicon.ico',

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // Set the production url of your site here
  url: 'https://eranyser.github.io',
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: '/CoreAndMore/',

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: 'eranyser', // Usually your GitHub org/user name.
  projectName: 'CoreAndMore', // Usually your repo name.

  onBrokenLinks: 'throw',

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  markdown: {
    mermaid: true,
  },

  themes: ['@docusaurus/theme-mermaid'],

  plugins: [
    function webpackWarningFiltersPlugin() {
      return {
        name: 'webpack-warning-filters',
        configureWebpack() {
          return {
            ignoreWarnings: [
              {
                message:
                  /Critical dependency: require function is used in a way in which dependencies cannot be statically extracted/,
                module: /vscode-languageserver-types[\\/]lib[\\/]umd[\\/]main\.js/,
              },
            ],
          };
        },
      };
    },
    [
      require.resolve('@easyops-cn/docusaurus-search-local'),
      {
        // Build-time index shipped with the static site (works on GitHub Pages)
        indexDocs: true,
        indexBlog: false,
        indexPages: false,
        language: ['en'],
        highlightSearchTermsOnTargetPage: true,
      },
    ],
  ],

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl:
            'https://github.com/eranyser/CoreAndMore/tree/main/apps/documents/',
          async sidebarItemsGenerator({defaultSidebarItemsGenerator, ...args}) {
            const items = await defaultSidebarItemsGenerator(args);

            function stripExcluded<T extends typeof items>(slice: T): T {
              const out = [] as unknown as T;
              for (const item of slice) {
                if (item.type === 'doc' && DOC_IDS_EXCLUDED_FROM_SIDEBAR.has(item.id)) {
                  continue;
                }
                if (item.type === 'category') {
                  const nested = stripExcluded(item.items);
                  if (nested.length === 0) {
                    continue;
                  }
                  out.push({...item, items: nested});
                  continue;
                }
                out.push(item);
              }
              return out;
            }

            return stripExcluded(items);
          },
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  themeConfig: {
    // Replace with your project's social card
    image: 'img/docusaurus-social-card.jpg',
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'My Site',
      logo: {
        alt: 'My Site Logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'knowledgeHubSidebar',
          position: 'left',
          label: 'Knowledge Hub',
        },
        //{to: '/blog', label: 'Blog', position: 'left'},
        {type: 'search', position: 'right'},
        {
          //href: 'https://github.com/facebook/docusaurus',
          href: 'https://github.com/eranyser/CoreAndMore',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            {
              label: 'Knowledge Hub',
              to: '/docs/definition',
            },
          ],
        },
        /*
        {
          title: 'Community',
          items: [
            {
              label: 'Stack Overflow',
              href: 'https://stackoverflow.com/questions/tagged/docusaurus',
            },
            {
              label: 'Discord',
              href: 'https://discordapp.com/invite/docusaurus',
            },
            {
              label: 'X',
              href: 'https://x.com/docusaurus',
            },
          ],
        },*/
        {
          title: 'More',
          items: [
            {
              label: 'GitHub',
              href: 'https://github.com/eranyser/CoreAndMore',
            },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} My Project, Inc. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
